### ISSUE TITLE
Attribute missing in the example

### ISSUE THREAD

**Issue by ericburner** [jakerieger/FlaskIntroduction#3]
hey Jake running through the code and getting'Todo' has no attribute 'date_created' this could be me but I cannot figure it out for the life of me.

**Comment by ericburner** [comment]
My bad, but I think following your video you call your object attribute db_created  at one point or I am just losing it =) .

**Comment by atharvjairath** [comment]
Hey! 
I tried , even I faced this issue. So I went on to download and run @jakerieger 's code. and tired to run `db.create_all()`
but I again got the error 

> AttributeError: can't set attribute

**Comment by jakerieger** [comment]
@atharvjairath

> 
> 
> Hey!
> I tried , even I faced this issue. So I went on to download and run @jakerieger 's code. and tired to run `db.create_all()`
> but I again got the error
> 
> > AttributeError: can't set attribute

If you're downloading this repo you don't need to run `db.create_all()` before running it. Checkout the instructions in the readme

**Comment by jakerieger** [comment]
Can you post the full console output when you receive this error? Running `db.create_all()` after importing `db` in to my python shell works just fine.

**Comment by atharvjairath** [comment]
> Can you post the full console output when you receive this error? Running `db.create_all()` after importing `db` in to my python shell works just fine. 

The issue was that I was using default python 2.7 in mac, while installing packages in pip3. I replaced my python 2.7 default to the latest one and now it running fine.

**Comment by Igor-Ono** [comment]
Hi @jakerieger , I got the same issue here. The error message was: 
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: todo.date_created`
On the following line:
```
else:
    tasks = Todo.query.order_by(Todo.date_created).all() # This one
    return render_template('index.html', tasks=tasks)
```
I did try to run the following piece of code several times in the terminal (after deleting test.db).
```
from app import db
db.create_all()
```
But the issue still persisted.
The problem was fixed by adding the following code portion before `@app.route('/', methods=['POST', 'GET'])`:
```
@app.before_first_request
def create_tables():
    db.create_all()
```
I am using PyCharm 2021.1.3 (Community Edition) and Python 3.7.
